### ISSUE TITLE
Non-identifier exports not detected?

### ISSUE THREAD

**Issue by evanw** [guybedford/cjs-module-lexer#47]
I came across some unexpected behavior:

```js
const cml = require('cjs-module-lexer')
cml.init().then(() => {
  const result = cml.parse(`module.exports = {fi, if: 0}`)
  console.log(result)
})
```

Expected:

```js
{ exports: [ 'fi', 'if' ], reexports: [] }
```

Observed:

```js
{ exports: [ 'fi' ], reexports: [] }
```

I expected this to work because ESM lets you do this:

```js
import { if as foo } from './example.js'
```

**Comment by evanw** [comment]
Wait, maybe it doesn't have anything to do with keywords. It looks like mapping to `null` works but mapping to `0` doesn't? Here are some tests with various expressions:

```js
module.exports = {fi, if: 0}
{ exports: [ 'fi' ], reexports: [] }

module.exports = {fi, if: !0}
{ exports: [ 'fi' ], reexports: [] }

module.exports = {fi, if: -0}
{ exports: [ 'fi' ], reexports: [] }

module.exports = {fi, if: (true)}
{ exports: [ 'fi' ], reexports: [] }

module.exports = {fi, if: [true]}
{ exports: [ 'fi' ], reexports: [] }

module.exports = {fi, if: null}
{ exports: [ 'fi', 'if' ], reexports: [] }

module.exports = {fi, if: true}
{ exports: [ 'fi', 'if' ], reexports: [] }
```

I guess this is because the grammar is specified as `` (IDENTIFIER (`:` IDENTIFIER )?) ``. Is there any reason to not support arbitrary expressions? Like `module.exports = { version: '0.1.0' }`.

**Comment by guybedford** [comment]
@evanw this is just a very simple lexer designed to be small and fast and it doesn't even have an expression parser. We could extend the grammar to support direct primitives in the object form, but for now I'm concerned that may be even more confusing too, it's not a clear line by any means yes. See also https://github.com/guybedford/cjs-module-lexer/issues/6.

Supporting numbers and strings would be straightforward, I'm just not sure we want to push the blurry line in that direction here, would value your thoughts.

**Comment by guybedford** [comment]
The latest update has been upstreamed now, and the object form detection remains the same without string support. I'm open to further suggestions here, although the window is closing on the current set of updates. Closing for now but just let me know if we should reopen or make changes here further.

**Comment by evanw** [comment]
> it doesn't even have an expression parser

Ah, this makes sense. I was mainly just surprised that support for this wasn't necessary to handle modules like that in the wild.

I recently shipped support for the `0 && module.exports = {...}` pattern in esbuild btw. So far so good.
