### ISSUE TITLE
Accept a change from a pull request at Node.js core repository

### ISSUE THREAD

**Issue by peZhmanParsaee** [guybedford/cjs-module-lexer#48]
Hi, good time.

I made a pull request to Node.js repository that fixes a typo in README.md file of the current repository. This is a link to that pull request:

https://github.com/nodejs/node/pull/37895

I am thankful if you accept those changes, or guide me through it.

**Comment by guybedford** [comment]
@peZhmanParsaee sure, can you post the PR to this repo? I likely won't roll out a patch release for this just yet though.
