### ISSUE TITLE
Also analyze requires

### ISSUE THREAD

**Issue by kriskowal** [guybedford/cjs-module-lexer#5]
I may be able to use this in a SES subproject. Ideally, I could use this and also eliminate a dependency on another parser used to heuristically analyze requires too.

**Comment by guybedford** [comment]
We're currently looking at moving this into the Node.js org with the goal of ensuring parity for the Node.js use case specifically. So maintaining other objectives for this project is a little bit of a tricky value proposition under that structure.

In addition, require analysis has it's own details:
* How to parse dynamic expressions and their analysis
* Whether to use scope analysis or not
* Whether to detect `const req = require` cases
* Whether to detect `require('module').createRequire()` cases as well

Then there is also `require.resolve` which typically needs to be analyzed along with require to handle asset references if the analysis is catering to those cases too.

For these reasons I'm tempted to say that the lexer should remain for exports only with this Node.js focus, and that the require extraction analysis should typically be the full scope-based analysis that does deeper execution checking that can eg handle require expression analysis.

**Comment by kriskowal** [comment]
Fair! Will mull.

**Comment by guybedford** [comment]
Agreed it would be a nice feature, and I know `require(...)` analysis goes a long way. But with the `const req = require` cases and that it's more about the organizational aspects, this may have to be one of those hard lines.
