### ISSUE TITLE
CommonJS import from a Module package too inflexible

### ISSUE THREAD

**Issue by k2snowman69** [guybedford/cjs-module-lexer#57]
I originally opened this over in https://github.com/nodejs/node/issues/39052 and was asked to move this here. Using the same structure since it has quite a bit of detail already.

* **Version**: v14.17.1
* **Platform**: Microsoft Windows NT 10.0.19042.0 x64
* **Subsystem**:

### What steps will reproduce the bug?

Whenever a consuming npm package is `type: module` it seems to be much picker about importing packages of which distribute cjs style code via `import { bar } from "../lib/factory.js";`. This limitation prevents consuming libraries from using `type: module` until all the dependent libraries are fixed and corrected which slows adoption.

To give an example I've created a repository https://github.com/k2snowman69/bug-nodejs-import-cjs which has two folders

 - lib - Contains trimmed down versions of three different styles of cjs outputs I've found (glob, dropbox and tslib). I stopped at three because it got the point across
 - use-lib - an ESM package that consume the three different styles of CJS outputs

### How often does it reproduce? Is there a required condition?

Every time across multiple versions of node

### What is the expected behavior?

When running any of the following:
- node .\use-lib\use-define-property.js
- node .\use-lib\use-factory.js
- node .\use-lib\use-function.js

All three succeed in executing. This would mean that even though a dependency of my project might not be written in ESM or be rewritten using the Object.defineProperty style of CJS, that I'm able to use ESM style for my particular project though lose on some of the major benefits if that dependency were written in ESM.

### What do you see instead?

If the commonjs library dist output uses the Object.defineProperty to build it's output, it works successfully, however the other two solutions seem to break.

```
PS D:\Projects\bug-nodejs-import-cjs> node .\use-lib\use-define-property.js
bar

PS D:\Projects\bug-nodejs-import-cjs> node .\use-lib\use-factory.js
file:///D:/Projects/bug-nodejs-import-cjs/use-lib/use-factory.js:1
import { bar } from "../lib/factory.js";
         ^^^
SyntaxError: Named export 'bar' not found. The requested module '../lib/factory.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../lib/factory.js';
const { bar } = pkg;

←[90m    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)←[39m
←[90m    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)←[39m
←[90m    at async Loader.import (internal/modules/esm/loader.js:177:24)←[39m
←[90m    at async Object.loadESM (internal/process/esm_loader.js:68:5)←[39m

PS D:\Projects\bug-nodejs-import-cjs> node .\use-lib\use-function.js
file:///D:/Projects/bug-nodejs-import-cjs/use-lib/use-function.js:1
import { bar } from "../lib/function.js";
         ^^^
SyntaxError: Named export 'bar' not found. The requested module '../lib/function.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../lib/function.js';
const { bar } = pkg;

←[90m    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)←[39m
←[90m    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)←[39m
←[90m    at async Loader.import (internal/modules/esm/loader.js:177:24)←[39m
←[90m    at async Object.loadESM (internal/process/esm_loader.js:68:5)←[39m
```

### Additional information

This is my first bug in such a public space and I'm a bit nervous, feel free to ask me to reorganize or cleanup the original description to make it easier to understand. Any suggestions would be great, I'm trying to get better at writing issues!

**Comment by guybedford** [comment]
Thanks for reporting the issue, and as you can likely tell there is quite a bit of complex reasoning for how we got here.

The short answer is that the cases you're talking about supporting like `function obj () {}; obj.foo = ...` are all cases where it's impossible to tell `foo` is an export _before_ the CommonJS has executed.

The restriction of needing to work out what a CommonJS module will export before we can execute it is one that was imposed by a combination of requirements from the ECMAScript modules spec itself to Node.js requirements, that were all fought and argued extensively.

While it is possible in theory to support these cases via static analysis, the other constraint this project has is to extract the list of exports incredibly quickly so there is no execution slowdown. More advanced code analysis to determine `obj` is a function that is later exported, that has properties applied, is simply out of the scope of this project unfortunately.

There are likely simple cases we can improve - eg we don't currently support `module.exports = { a: 1 }`, simply because a number on the value side of an object expression isn't yet supported by the parser. So if you hit simpler cases where your eyes don't need to understand JavaScript execution to easily see what is exported (about the level of this project), then we can certainly add support for those.

Let me know if that answers your question and sorry we can't do better than this.

**Comment by k2snowman69** [comment]
I think it answers my questions and makes sense why an eval is completely out of the question but there might be more that we could do depending on what this package is willing to parse. A few ideas that I'll organize based on the example package:

### tslib

[unpkg link to package contents](https://unpkg.com/browse/tslib@2.3.0/)

1. Though tslib is a cjs library, in it's package.json it does define the `module` property which (though not in the node spec) is often defined to mean esm style exports. Could this be used to aid this library in populating what should be coming from the commonjs dist output?
2. Similar line of thought, tslib also contains a tslib.d.ts which can be referenced by the `typings` property in the package.json. Maybe this could be parsed to help aid the knowledge of what is coming out of the module?

### glob

[unpkg link to package contents](https://unpkg.com/browse/glob@7.1.7/)

I'll admit I don't have any smart ideas for this one

### enzyme

[unpkg link to package contents](https://unpkg.com/browse/enzyme@3.11.0/)

I think this is actually one of those cases where "if you hit simpler cases where your eyes don't need to understand JavaScript execution to easily see what is exported" since the exported file contains the following:
```
module.exports = {
  render: _render2['default'],
  shallow: _shallow2['default'],
  mount: _mount2['default'],
  ShallowWrapper: _ShallowWrapper2['default'],
  ReactWrapper: _ReactWrapper2['default'],
  configure: _configuration.merge,
  EnzymeAdapter: _EnzymeAdapter2['default']
};
```
which should be pretty easy to parse.

**Comment by guybedford** [comment]
Agreed it would be nice to parse the enzyme one. There's actually a way we could support this in the parser I think, although it would be an interesting new parser approach... are you interested in working on the parser?

**Comment by k2snowman69** [comment]
As much as I'd love to I simply wont have time. This is only one of multiple issues I'm running into while trying to move my org to be able to use ESM. Currently hunting and debugging each one to open tickets in all the respective projects (as you can see from the investigation above I'm going package by package) is very time consuming. 

I'll try to loop back when time opens up in case it hasn't been tackled but I'd estimate months out at this point.

**Comment by guybedford** [comment]
Ok I've posted https://github.com/guybedford/cjs-module-lexer/issues/58 which we can leave open to track the specific support for whenever whomever has time! Thanks again for the comments.
