### ISSUE TITLE
add tag for 1.2.2

### ISSUE THREAD

**Issue by Trott** [guybedford/cjs-module-lexer#60]
In the Node.js docs (in esm.md), there is a link to https://github.com/guybedford/cjs-module-lexer/tree/1.2.2 but that link 404's because there is no tag/release in GitHub for 1.22. Can you add one?

**Comment by guybedford** [comment]
Done, thanks for noticing. Btw I would still want to transfer this project into the Node.js org / extend permissions on it. If anyone wants to be added as a maintainer just let me know too.

**Comment by Trott** [comment]
> Done, thanks for noticing. Btw I would still want to transfer this project into the Node.js org / extend permissions on it. If anyone wants to be added as a maintainer just let me know too.

I don't want to be added as a maintainer, but I would support moving it into the nodejs org.  There's a checklist somewhere (basic stuff--have a README, have a compatible LICENSE, have a CoC, that sort of thing) but the main thing to do is to open an issue in the admin repo. (Maybe you already did that? In which case I'll happily +1 it and/or do what I can to get it unstuck.)

**Comment by targos** [comment]
Documentation is here: https://github.com/nodejs/admin/blob/main/transfer-repo-into-the-org.md

**Comment by guybedford** [comment]
If someone wants to run through the checklist there I will gladly give the necessary access to do the process.
