### ISSUE TITLE
False exports detections

### ISSUE THREAD

**Issue by barak007** [guybedford/cjs-module-lexer#7]
I don't know if its wrong for this lexer to pick up none valid module exports but this code should not report `y` as an export.
I guess it's because it's un aware of scopes and variable declarations.
```js
function fake(module){
    module.exports.y = 1
}
fake({exports: {}});
```

**Comment by guybedford** [comment]
Yes, as described in https://github.com/guybedford/cjs-module-lexer#named-exports-parsing the lexer will overclassify.

If you have a specific example you think is a bad overclassification happy to discuss further, but otherwise this is by design yes.
